name: Build and Push GolGana Images

on:
  push:
    branches:
      - master  # se ejecuta automáticamente en cada push a master
  workflow_dispatch:  # también permite ejecutarlo manualmente

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend image
        run: docker build -t enzomiretti1/golgana-backend:latest DespliegueGolGana-main/appdemo/backend

      - name: Push backend image
        run: docker push enzomiretti1/golgana-backend:latest

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build frontend image
        run: docker build -t enzomiretti1/golgana-frontend:latest DespliegueGolGana-main/appdemo/frontend

      - name: Push frontend image
        run: docker push enzomiretti1/golgana-frontend:latest
